### ISSUE TITLE
Some travel lines renders as extrusion lines

### ISSUE THREAD

**Issue by o0Ghost0o** [remcoder/gcode-preview#100]
Hi, I've encounter a bug when setting the lineWidth to anything, if I leave the GCodePreview.init({}) settings without the lineWidth it won't render those travel lines

Without the lineWidth parameter
<img width="1095" alt="ScreenShot1" src="https://github.com/remcoder/gcode-preview/assets/86219777/b57132ca-37fd-457f-8117-8b5253da1b51">

With the lineWidth parameter to 1
<img width="1094" alt="ScreenShot2" src="https://github.com/remcoder/gcode-preview/assets/86219777/6b341d33-561d-4714-b5f9-f0a52e547df3">

**Comment by remcoder** [comment]
thx for reporting @o0Ghost0o. I'll take a look at this.

**Comment by remcoder** [comment]
@o0Ghost0o this is [fixed in v2.13](https://github.com/remcoder/gcode-preview/releases/tag/v2.13.0).

**Comment by o0Ghost0o** [comment]
@remcoder, nice, wish all bugs were like that xD. Thank you!, btw, I can give you an example for vue3 using <script setup> too (need to make the template as I'm using it with laravel).

**Comment by remcoder** [comment]
@o0Ghost0o that would be awesome! 

Not sure what you had in mind but I think you could maybe either send a PR to:
- add a new vue example
OR
- add a section to the README

Feel free to [open a ticket](https://github.com/remcoder/gcode-preview/issues/new/choose) too if you want.
