### ISSUE TITLE
Update framework examples for v3

### ISSUE THREAD

**Issue by remcoder** [remcoder/gcode-preview#108]
- [ ] React example
- [ ] Vuejs
- [ ] Svelte

Should use latest versions of the lib, the framework, node, vite. Let's also doublecheck we're using the canonical starter kit for the respective frameworks.

**Comment by remcoder** [comment]
@sophiedeziel  Suggestion to move them to separate repos. This has many benefits:
 - easy to 'deploy on push'
 - no more dependabot clobbering the main repo
 - easy to fork for reproduction scenarios
 - less clutter in the main lib

This might be a prompt to move the lib to an org!

**Comment by sophiedeziel** [comment]
I agree with everything in that last comment. We talked about this in the past. 

It requires effort to setup all the different repos with the dependabot/deploy setup that we have. But it may be worth it on the long run.
