### ISSUE TITLE
extrusionColor: Ability to set colour at extrusion line-level

### ISSUE THREAD

**Issue by tom-walkr** [remcoder/gcode-preview#120]
It would be incredibly useful to be able to set extrusionColor selectively for each extrusion line. The previewer could take an array of hex strings as an argument and map these to corresponding extrusion lines.

This would enable selective colouring of G-code features (walls, infill, etc.), and give greater aesthetic control. 

Myself and my colleagues can work on this, but if anyone is working on this already, or has a plan to, please shout!

**Comment by sophiedeziel** [comment]
I also wish that would be possible and have some ideas on how to do it.

First of all, the internal structure and API assume layers and have them built in, with rigid attributes for color. I don't think this should stay long term, but it's the most common paradigm today and making breaking changes on this is a very hard sell. I don't think it's the responsibility of the library to be able to parse slicer-specific metadata for distinguishing infil, walls, etc, but it already has a precedent.

Without breaking everything, I have ideas on how to manage chunks of gcode by passing arguments instead of letting the library calculate everything. I mentioned it on the project's Discord last week 😄 .

I'm playing with the idea of a re-architechture and plan on building a prototype soon, which would enable this specific feature request. I'm really curious about how you envision this. Would the mapping be `zip` style or you're thinking about passing line numbers along with the hex? Maybe labels? 

I think that this feature should not be rushed and many designs should be considered.

**Comment by tom-walkr** [comment]
Agree the library should not be responsible for parsing slicer-specific data - responsibility should be on user here, as too complex to cater for all configurations.

My initial thought was passing in an array with a `zip`-like mapping, but now that you mention it, I see merit in the approach whereby line numbers are passed in with a hex. From a user's perspective, generating these inputs would likely be quicker and easier for small sections. All lines not mentioned in array would then take on the 'global' `extrusionColor`.

**Comment by remcoder** [comment]
Maybe I'm missing something but I'm not yet sold on passing, from what I understand, a huge data structure to the lib. And wouldn't this also require the consumer of the lib to do their own parsing of the gcode?

I'm all for protecting the responsibilities of the lib but I also see merit in adding some logic to the parser to interpret comments like `;TYPE:Skirt/Brim` to color extrusion lines accordingly. 

So let's say whenever the line `;TYPE:Skirt/Brim` is encountered the current extrusion color would switch to the color for brims. And so on. 

The parser can translate such lines into a new command type for this purpose, say a SetColorCommand. (This would even work nicely when we come to rendering multi-color prints, solving it in the parser entirely.)

To make it more slicer-agnostic a dictionary could be passed that maps strings (or regex's) to colors. 
```
{
 ';TYPE:Skirt/Brim' : '#ff0000',
 ';TYPE:Perimeter' : '#00ff00',
 ';TYPE:External perimeter' : 'pink'
}
```

I'm also not against collecting several  such dictionaries for different slicers in a contrib folder.

I'm curious what you guys think.

**Comment by remcoder** [comment]
In either scenario, we need to take into account incremental gcode processing. It's possible to have this sequence:
- preview init
- processGCode( .. gcode .. )
- processGCode( .. more gcode .. )
- etc

It's even possible the entire gcode is not known beforehand. Like when it is being streamed in chunks from server to client for instance.

**Comment by sophiedeziel** [comment]
> To make it more slicer-agnostic a dictionary could be passed that maps strings (or regex's) to colors.
>
> ```javascript
> {
>  ';TYPE:Skirt/Brim' : '#ff0000',
>  ';TYPE:Perimeter' : '#00ff00',
>  ';TYPE:External perimeter' : 'pink'
> }
> ```
> I'm also not against collecting several such dictionaries for different slicers in a contrib folder.

I love that approach. It's the perfect middle ground IMO. With that as a starting point, I think it's important to consider when blocks have starting and ending lines and if we want to go wild and allow nestest blocks. I may be carried away with enthusiasm, but imagine:

```javascript
[
  {
    'blockStart': \;MESH:box.stl\,
    'blockEnd': \;MESH:NONMESH\,
    'rules': [
      {
          'blockStart': ';TYPE:WALL-OUTER',
          'blockEnd': \;TYPE:*+\,
          'color': 'pink'
      }
    ]
  },
  {
    'blockStart': \;MESH:lid.stl\,
    'blockEnd': \;MESH:NONMESH\,
    'rules': [
      {
          'blockStart': ';TYPE:WALL-OUTER',
          'blockEnd': \;TYPE:*+\,
          'color': 'orange'
      }
    ]
  },
  {
      'blockStart': ';TYPE:WALL-OUTER',
      'blockEnd': \;TYPE:*+\,
      'color': 'blue'
  }
]
```

I know it may be overkill.

But it allows for having a pink outerwall for the box, an orange lid, and everything else on the build plate is blue.

**Comment by remcoder** [comment]
Well we could start with blockStart and color and leave the door open to a possible extension.
```
{
      'blockStart': ';TYPE:WALL-OUTER',
      'color': 'blue'
}
```

We'd only need blockEnd if we're nesting right? 

I'm skeptical about a usecase where you both want to color objects and line types. Let's also think about what we want to visualize. If we want to identify walls, it makes sense to have them all of the same color so as to easily spot them all. So from a UX perspective, I'm leaning more towards coloring either lines types or objects (or extruder number) but not a combination. 

@tom-walkr was there a particular reason you suggested setting colors at the line-level? From the mentioned solutions would work for you?

**Comment by sophiedeziel** [comment]
> We'd only need blockEnd if we're nesting right?

It depends on our closing logic. It's safe to assume that any `;TYPE:` ends by defining another `;TYPE:`, but it might not be what the user wants to have. `;MESH:foo.stl` ends with `;MESH:NONMESH`, with is an explicit closing mark. 

Different slicers may have different logic, so I don't see how we can go without specifying a closing mark, or at least make it optional. The nesting logic is just some extra on top of it.

**Comment by tom-walkr** [comment]
Our use case is to colour lines so we can geometrically display print quality information that we generate during printing, which I admit is rather specific!

We have actually achieved what we need the library to do by adapting `addThickLine()` to take an array of colours (mapped to cartesian coordinates), generated by us, to selectively colour each vertex.

However, the ability to selectively colour different line types would also be very useful, and I would support the idea to add this as functionality to the public repo.

**Comment by sophiedeziel** [comment]
I'm bringing back the point of rendering colors based on something that is not found directly in the GCode, but passed in as line numbers, or something else.

I have some use cases that will help understand.

- Let's say I have a text editor and the preview side by side. It would be nice to have lines that are selected in the editor highlighted in the preview. `{ 'startLine': 102, 'endLine': 124, 'color': 'blue' }`

- Another use case would be that the user has a collision detector of printed parts with the hotend. Those segments could be highlighted in red by passing a similar array of segments to color.

- Or bridges longer than a threshold. 

- Lines printed in mid-air

- Different colors for different layer heights

The idea would be to let the user define the logic for colors, and the lib to define the interface for the set of rules, priority and a polyvalent structure for start/finish

**Comment by sophiedeziel** [comment]
On a different aspect of this feature, do we want to also consider applying colors after the gcode is rendered? There could be some public methods to reset colors and apply them. Here's a scrappy example for the text editor use case above:

```javascript
const preview = new GCodePreview.init({...});
preview.processGCode(some_gcode);

function handleLinesSelected(lineStart, lineEnd) {
  preview.clearColors();
  preview.addColorRule({
    lineStart: lineStart,
    lineEnd: lineEnd,
    color: 'light blue'
  });
  preview.render();
}
```

**Comment by remcoder** [comment]
Trying to summarize then:
- no need right now to color _every_ line individually
- would be nice to color _some_ lines by _line number_, as per above. Please open a ticket for that if you want.
- coloring per _line type_ is definitely wanted but should be a separate issue.

please correct me if I'm wong

**Comment by remcoder** [comment]
Closing this issue for now as there seems no pressing reason to start development on this. 

Feel free to re-open if you think otherwise.
