### ISSUE TITLE
Collect flavours of multi-color (/ multi-material) gcode

### ISSUE THREAD

**Issue by remcoder** [remcoder/gcode-preview#123]
We want to support multi-color prints (#122). To get started we need an overview of the different flavours of multi-color printing and a few example gcode files to go with that.

So we're looking for example gcode files that use T1,T2,...Tx (tool change) for multi-color printing.

Examples collected:
- [ ] Prusa MMU
- [x] Prusa XL
- [ ] Bambulab AMS
- [x] IDEX (ex Sovol sv04)
- [ ] Enraged Rabbit Carrot Feeder
- [ ] Chameleon

Please drop your files [in this google drive](https://drive.google.com/drive/u/1/folders/1DOE_MRwTYm9Vfm32idmvpQdgxkNZpKyk)

**Comment by remcoder** [comment]
Thinking out loud here:

- Tx: requires mapping of color per _index_ (the x) ex `{ 1: 'red', 2: 'green' }`
- M600: requires a sequence of colors. The sequence may need to contain repetition: ['red', 'green', 'red']
-

**Comment by sophiedeziel** [comment]
I'll generate some as soon as possible.

**Comment by remcoder** [comment]
I have the feeling this isn't so much of an issue really. Ok if we close it?

**Comment by sophiedeziel** [comment]
Let's do it. There are many other ways to learn more.
