### ISSUE TITLE
3d line display for each layer

### ISSUE THREAD

**Issue by jeffkyjin** [remcoder/gcode-preview#14]
Do you have any plan to add 3d layer display in your viewer?
Now each layer is display as a line, it do not look clearly in slices 3d view.

**Comment by remcoder** [comment]
Well I have been playing with thicker lines but ran into issues so I've
parked that for now.

I'd like a real 3d look to be implemented at some point but I cannot say
when I get around to it.

If you, or anyone else, would want to contribute in this area I'd be happy
to help wherever I can.

Op ma 13 jul. 2020 16:33 schreef JIN Tao <notifications@github.com>:
