### ISSUE TITLE
Purge Line does not seem to be rendered

### ISSUE THREAD

**Issue by kyleisah** [remcoder/gcode-preview#142]
Hey there! 

I'm working on a simple little python script that will help users generate a nice beefy line purge to prime the nozzle prior to printing.

I can see the preview of the line purge in my typical slicer, but when I try to render it in your gcode previewer live demo, it doesn't seem to show up. Not sure if it has something to do with where gcode starts being read, but figured it should be mentioned.

Here's the gcode rendered in Prusaslicer's previewer:

![image](https://github.com/remcoder/gcode-preview/assets/40312912/9cd5bb2f-4693-4e91-a753-6b42683895ae)

And here's how it's rendered in your live demo:

![image](https://github.com/remcoder/gcode-preview/assets/40312912/19b4c11c-0c1e-4698-9da2-c0c9a4d57c85)

I'll also drop the sliced gcode file here, as a .txt,

[Shape-Cylinder-9.52316g-24m.txt](https://github.com/remcoder/gcode-preview/files/15141077/Shape-Cylinder-9.52316g-24m.txt)

Thanks so much! If you need anything else, let me know!

**Comment by remcoder** [comment]
Hi @kyleisah, thanks for bringing this to our attention. We'll be taking a look at it soon.

**Comment by remcoder** [comment]
Just found out that the purge line isn't rendered bc GCode Preview doesn't like spaces right before the numerical params.

So, this original snippet doesn't render a line:
```
G0 X95 Y 99.2894
G0 Z 0.8
G1 X155 E 50.0  F 718.42
```

While this version with the spaces removed _does_ render a line:
```
G0 X95 Y99.2894
G0 Z0.8
G1 X155 E50.0  F718.42
```

Should be fixed soon in the parser. As a temporary solution you can remove the spaces for now.

**Comment by kyleisah** [comment]
Nice work! The additional spaces are something the script seems to be doing, I'll see if I can add some stuff to remove trailing spaces after the axis and feedrate denominations are printed out. Thanks again!

**Comment by kyleisah** [comment]
Sweet, fixed my script. Was escaping the print function to print variables and it all got so confusing. fstrings to the rescue!
![image](https://github.com/remcoder/gcode-preview/assets/40312912/b26eb141-b590-447a-b7f7-be845fd0c979)

**Comment by remcoder** [comment]
That's great! And thank you for reporting back. 

I'll keep this open so we'll fix this issue in the parser at some point.

Good luck with those beefy purge lines! 😉

**Comment by kyleisah** [comment]
Cheers!
