### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by sophiedeziel** [remcoder/gcode-preview#153]
I'm thinking about adding a dev mode to display some informations on the screen that would help the development of features. 

Just a rectangle on the top right corner to show some stats and toggle some dev features.

- Time to render
- Size of the gcode
- Number of travel moves
- Number of extrusion moves
- Number of triangles on the scene
- Number of groups
- Camera position
- Toggle wireframe mode
- Toggle some `console.log` outputs

This can be done incrementally

**Comment by remcoder** [comment]
Great idea!

Would be useful for non-dev users too.
