### ISSUE TITLE
Some lines are not rendered properly

### ISSUE THREAD

**Issue by sophiedeziel** [remcoder/gcode-preview#216]
The only way I found to reliably reproduce is using the CNC preset, but it also happens sometimes when rendering travel lines.

<img width="1680" alt="Screenshot 2024-10-11 at 19 30 24" src="https://github.com/user-attachments/assets/b5f4eb60-342c-45c2-9b6b-63bc5c73bd5c">

It is hard to see, but it seems like the lines are on the scene. They are just so small we can't see them. We can notice some green pixels.

**Comment by remcoder** [comment]
This might be since the bump to threejs r169. Let's check that first.

**Comment by sophiedeziel** [comment]
I tried downgrading the lib multiple times, I'm not sure it's that.

I think you should try because there is probably something I did wrong

**Comment by remcoder** [comment]
Found the problem: setting the lineWidth (thickLine) is broken when using r165+
