### ISSUE TITLE
Update the readme/doc according to the different changes bundled in the next release

### ISSUE THREAD

**Issue by sophiedeziel** [remcoder/gcode-preview#240]
Self-explanatory title. 😸

**Comment by remcoder** [comment]
GitHub auto release notes + chatgpt ftw!😉

**Comment by sophiedeziel** [comment]
But I double-checked the readme. There are some code snippets but I think none of them are affected. 

I'll check again carefully testing them to make sure they're working as advertised.

**Comment by sophiedeziel** [comment]
Just a random thought:

Should there be a specific test file that verifies all code snippets in the readme are always valid? That would be great as a reminder to update them when needed! 

Or a more generic API schema test that alerts of API breaking changes. It could be ran separately on github actions to apply a label to a PR.

**Comment by sophiedeziel** [comment]
Double-checked all snippets in the readme. They're still valid, all of them.
