### ISSUE TITLE
Is there a way to make gcode in a LineTubeGeometry have different radius

### ISSUE THREAD

**Issue by jane-rose** [remcoder/gcode-preview#29]
See image as below. If we want to display the LineTubeGeometry of the `inner wall`, hide the line corresponding to the gcode of `travel`. Change the radius does not work. Thanks.
<img width="530" alt="4B8E7F7E-86AB-4C6E-BBB6-5746A8488DA1" src="https://user-images.githubusercontent.com/33253363/161882142-32e5748f-2541-40dc-8ed1-8085a2d86dea.png">

**Comment by remcoder** [comment]
Hoi @jane-rose, try making different segments. 1 segment for travel and 1 segment for extrusion. Then you can render them individually with a different radius and a different color.

btw, nice project you are working on!
