### ISSUE TITLE
I would love to enable the autorotate feature of the orbit controls. 

### ISSUE THREAD

**Issue by Vizeo** [remcoder/gcode-preview#37]
Can you expose the orbit controls so that I can turn on the camera controls. Am making a dashboard that will have widgets displaying what is currently printing on my printers and it would be great to have them spin.

**Comment by remcoder** [comment]
Hi @Vizeo, I've exposed the controls in PR #38. To make it work you only need to set `.autoRotate = true`. Let me know if this is what you want and I'll merge it.

**Comment by remcoder** [comment]
@Vizeo just published v2.8.0 that exposes the `.controls`. HTH!
https://www.npmjs.com/package/gcode-preview/v/2.8.0
