### ISSUE TITLE
Module '"gcode-preview"' has no exported member 'GCodePreview'.

### ISSUE THREAD

**Issue by Zeng95** [remcoder/gcode-preview#39]
Hi there. First of all, the library is really nice and helpful. However, I'm facing a TypeScript error as shown below while integrating it into my project.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/12603244/193776770-26cba6fc-c063-4a10-8a91-2920c961820b.png">

**Comment by remcoder** [comment]
Which version are you using? 

Try `import * as GCodePreview from 'gcode-preview'` for 2.8.x

In develop I'm working on 3.0 which breaks things

**Comment by Zeng95** [comment]
> Which version are you using?
> 
> Try `import * as GCodePreview from 'gcode-preview'` for 2.8.x
> 
> In develop I'm working on 3.0 which breaks things

2.8.1 -> the latest one

**Comment by Zeng95** [comment]
![image](https://user-images.githubusercontent.com/12603244/193868422-f28fdd13-f9ef-44f7-9aaa-f46e363f09b0.png)
![image](https://user-images.githubusercontent.com/12603244/193868452-5c9de6af-3131-4b41-aba1-cb3b4b04fd3c.png)

**Comment by remcoder** [comment]
I find I have to reload VS Code before it sees my changes. Maybe that works for you.

I tried a fresh project but I cannot reproduce the type error. Does it build?

Maybe I can help of you create a repo with the issue, if possible.

**Comment by remcoder** [comment]
Oh I see the problem. You should be using `.init`

```
import * as GCodePreview from 'gcode-preview'

GCodePreview.init({
   canvas: CanvasRef.current as HTMLCanvasElement
})
```

**Comment by Zeng95** [comment]
> Oh I see the problem. You should be using `.init`
> 
> ```
> import * as GCodePreview from 'gcode-preview'
> 
> GCodePreview.init({
>    canvas: CanvasRef.current as HTMLCanvasElement
> })
> ```

Thank you! I'll try it our and let you know if it works

**Comment by Zeng95** [comment]
> Oh I see the problem. You should be using `.init`
> 
> ```
> import * as GCodePreview from 'gcode-preview'
> 
> GCodePreview.init({
>    canvas: CanvasRef.current as HTMLCanvasElement
> })
> ```

It works! Awesome! THANK YOU

**Comment by remcoder** [comment]
Happy to hear!
