### ISSUE TITLE
react-typescript-demo/react-scripts: not found

### ISSUE THREAD

**Issue by gpantalos** [remcoder/gcode-preview#47]
I am trying to run the demo using `npm start` from the `react-typescript-demo` directory and keep getting this error
```
> react-typescript@1.0.0 start
> react-scripts start

sh: 1: react-scripts: not found
```

**Comment by remcoder** [comment]
You'll need to run `npm install` first. Make sure you run this from _inside_ the `react-typescript-demo` folder.

HTH! :-)

**Comment by remcoder** [comment]
Docs updated in https://github.com/remcoder/gcode-preview/commit/164222474ec565d671eba4225f34526c576bada9
