### ISSUE TITLE
Rendering G00 movements in a different color

### ISSUE THREAD

**Issue by IGMontero** [remcoder/gcode-preview#62]
Hello!

First time using this lib, I want to render a .ngc file. It contains G00 commands and I want to remove them or show them in a different color, is this possible?

Just as an example:

How my ngc file is rendered:

![Screenshot 2023-07-21 at 13 03 51](https://github.com/remcoder/gcode-preview/assets/33161734/c8a72e78-6983-4c31-a8e3-65aa62e777a3)

How I want to render it (ngc viewer):

![Goo](https://github.com/remcoder/gcode-preview/assets/33161734/9edb2841-9a91-4e38-8b9c-32926e99e0cb)

Any help/direction is highly appreciated!!

**Comment by remcoder** [comment]
Hi there!

I've added an option to specify which moves are nonTravelMoves and published a new version.
See [here for an example](https://github.com/remcoder/gcode-preview/releases/tag/v2.9.4).

https://www.npmjs.com/package/gcode-preview/v/2.9.4

**Comment by IGMontero** [comment]
Hey, that was fast, thank you very much! Highly appreciate your response and turnaround time.
