### ISSUE TITLE
Possibility to change color of model

### ISSUE THREAD

**Issue by ivan-hryshko** [remcoder/gcode-preview#80]
Give the opportunity to change the color of the model, because now it is gray by default. Is it possible to change this with parameter passing?

**Comment by remcoder** [comment]
Hi @ivan-hryshko , setting the extrusion color is not yet possible.

I can add it for you.

Would you like something like this?

yellow, 50% saturation, , brightness [0, 80]
<img width="353" alt="image" src="https://github.com/remcoder/gcode-preview/assets/461650/e26f285c-1773-43c6-b449-2dd3ef24cf6d">

red, 50% saturation, brightness [0, 80]
<img width="274" alt="image" src="https://github.com/remcoder/gcode-preview/assets/461650/92d4746f-c375-46e2-862c-58ddbdf514f6">

purple, 100% saturation, brightness [20, 80]
<img width="267" alt="image" src="https://github.com/remcoder/gcode-preview/assets/461650/c4df7c34-baef-4c15-be67-692fa67b7e33">

I'm thinking about a param to override the Color, which will determine the hue and the saturation. The brightness will still be based on the layer height. How is that?

Also see the current [code for the gradient](https://github.com/remcoder/gcode-preview/blob/develop/src/webgl-preview.ts#L221-L224).

**Comment by ivan-hryshko** [comment]
@remcoder Looks cool, I like it)
The transfer of hue and saturation will be enough for my needs.
Although if you add the ability to set the brightness [20, 80] as you have shown, that would be an added plus as well.
Please let me know when this feature will be added

**Comment by remcoder** [comment]
Just released 2.10 with these changes (cc @ivan-hryshko )

**Comment by ivan-hryshko** [comment]
@remcoder 
Thank you very much. It looks great.
But is it possible to pass a custom range for brightness as you suggested above?
Because I have a problem with displaying black, gray and white.
Is it possible to set for:
black color for example brightness in the range [0-30]%
for gray [30-70]%
And for white [70-100]%
