### ISSUE TITLE
Element not destructible!

### ISSUE THREAD

**Issue by Paralelopipet** [remcoder/gcode-preview#84]
First of all I would like to thank the developers of gcode-viewer for the marvelous work and keeping this project maintained. Gcode-viewer really boosted my development speed and enabled me to focus on developing other parts of the software while having trust in this library to display and enable users easy interaction with the gcode. @remcoder 

Straight to the point! I have a web-page on which a customer can select any on the listed gcodes and they do so the new Vue element containing gcode-viewer is displayed. When the gcode-viewer is represented as a Vue component on a web page and I attempt to destroy it (in order to make a new one) even though it seems to be destroyed the animation keeps running in the background as destruction was incomplete due to infinite animate loop.

I have solved this problem by rewriting the animation loop on the Vue level in the following fashion:

```javascript
// Define animate function with stop condition
  this.preview.animate = () => {
    if (this.renderingBool) {
      this.preview.controls.update();
      this.preview.renderer.render(this.preview.scene, this.preview.camera);
      // check if the still exists before calling the next animation frame
      requestAnimationFrame(() => {
        if (this.renderingBool) {
          this.preview.animate();
        }
      });
    }
  };
 // Destructor
  public beforeDestroy() {
    // stop the animation loop
    this.renderingBool = false;
  }
```

This works for me but it would be much nicer to have it inside gcode-preview.js as a part of destructor so that future users don't need to define custom animation loops. Would love to put in on js level myself but I noticed that the file is likely generated, therefore I am leaving the task to the main dev team. If you need any further ideas or guidance I am available and happy to help!

**Comment by remcoder** [comment]
Thank you @Paralelopipet  for your kind words! This is surely something that should be fixed at some point.

To move this forward consider sending a PR.

The js code is generated from the typescript source. To get started,  [the animate function can be found here](https://github.com/remcoder/gcode-preview/blob/develop/src/webgl-preview.ts#L211-L215).
